# Generated by Django 3.2.6 on 2021-08-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=100)),
                ('catSumProducts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodID', models.IntegerField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=100)),
                ('prodDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('prodPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prodRange', models.IntegerField(blank=True, null=True)),
                ('prodDelivery', models.CharField(choices=[('Delivery', 'Delivery'), ('Drop Pin', 'Drop Pin'), ('House Call', 'House Call')], default='Drop Pin', max_length=10)),
                ('prodPicture', models.ImageField(upload_to='Photos')),
                ('prodLive', models.BooleanField()),
                ('servTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Saved on')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('userUniversity', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=20)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('tierID', models.IntegerField(primary_key=True, serialize=False)),
                ('tierName', models.CharField(blank=True, max_length=100, null=True)),
                ('tierDescription', models.CharField(max_length=250)),
                ('tierPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=100)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('securityID', models.IntegerField(primary_key=True, serialize=False)),
                ('securityGuardPresence', models.BooleanField()),
                ('locationCrowdPresence', models.CharField(choices=[('No Crowd Presence', 'No Crowd Presence'), ('Moderate Presence (5-10 people in vicinity)', 'Moderate Presence (5-10 people in vicinity)'), ('Vast Presence (10+ people in vicinity)', 'Vast Presence (10+ people in vicinity)')], default='Vast Presence (10+ people in vicinity)', max_length=100)),
                ('locationCrowdMovement', models.CharField(choices=[('Little to No Movement (e.g Library', 'Little to No Movement (e.g Library'), ('Mild Movement (e.g Coffee Shop )', 'Mild Movement (e.g Coffee Shop'), ('Vast Presence (e.g bus stop, mall)', 'Vast Presence (e.g bus stop, mall')], default='Mild Movement (e.g Coffee Shop )', max_length=100)),
                ('safe', models.BooleanField()),
                ('userReports', models.CharField(max_length=250)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.location')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('savedID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateSaved', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Saved on')),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('reviewStars', models.IntegerField(blank=True, null=True)),
                ('reviewDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=100)),
                ('orderNote', models.CharField(blank=True, max_length=250, null=True)),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity', models.CharField(max_length=100)),
                ('orderDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ordered on')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.location')),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='DropPin',
            fields=[
                ('dropPinID', models.IntegerField(primary_key=True, serialize=False)),
                ('dropPinName', models.CharField(max_length=19)),
                ('dropPinUniversity', models.CharField(max_length=100)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.location')),
                ('securityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.security')),
            ],
        ),
    ]
