# Generated by Django 3.2.6 on 2021-08-10 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodPicture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photos'),
        ),
    ]
