# Generated by Django 3.2.6 on 2021-08-10 21:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_prodpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodDelivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodRange',
        ),
        migrations.RemoveField(
            model_name='product',
            name='servTime',
        ),
        migrations.RemoveField(
            model_name='store',
            name='prodID',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='userID',
        ),
        migrations.AddField(
            model_name='product',
            name='prodSaved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='storeDelivery',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Drop Pin', 'Drop Pin'), ('House Call', 'House Call')], default='Drop Pin', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodPicture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='prodPicture'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tierDescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tierName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.IntegerField(primary_key=True, serialize=False)),
                ('purchaseTotal', models.DecimalField(decimal_places=2, max_digits=50)),
                ('orderDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ordered on')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.location')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.order')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
    ]
