# Generated by Django 3.2.6 on 2021-08-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210810_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
