# Generated by Django 3.2.6 on 2021-08-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210810_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='tierPrice',
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('optionID', models.IntegerField(primary_key=True, serialize=False)),
                ('optionName', models.CharField(max_length=100)),
                ('optionPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tierID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.tier')),
            ],
        ),
    ]
